# Generated by Django 5.0.6 on 2024-06-22 22:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='product',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inquiryreason',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reportparameters',
            name='response_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reportparameters',
            name='subject_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='searchparameters',
            name='bvn_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='searchparameters',
            name='search_type',
            field=models.CharField(max_length=50),
        ),
    ]
