# Generated by Django 5.0.6 on 2024-06-24 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_request_created_at_alter_application_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('addr_type', models.CharField(max_length=50)),
                ('date_reported', models.DateTimeField()),
                ('sno', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationInsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_overdue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('approved_credit_sanctioned', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(max_length=10)),
                ('institution_type', models.CharField(max_length=100)),
                ('legal_flag', models.CharField(max_length=10)),
                ('no_of_accounts', models.IntegerField()),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationProdType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_overdue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(max_length=10)),
                ('no_acc_last_six_mon', models.IntegerField()),
                ('no_of_accounts', models.IntegerField()),
                ('product_type', models.CharField(max_length=100)),
                ('sanctioned_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_outstanding_balance', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='ClosedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_status', models.CharField(max_length=50)),
                ('cf_closing_date', models.DateTimeField()),
                ('credit_facility_type', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=50)),
                ('institution_name', models.CharField(max_length=200)),
                ('legal_action_status', models.CharField(max_length=50)),
                ('sanction_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sno', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ConsCommDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('identifier_number', models.CharField(max_length=50)),
                ('id_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='requestparameters',
            name='application',
        ),
        migrations.RemoveField(
            model_name='requestparameters',
            name='inquiry_reason',
        ),
        migrations.RemoveField(
            model_name='requestparameters',
            name='report_parameters',
        ),
        migrations.RemoveField(
            model_name='request',
            name='request_parameters',
        ),
        migrations.RemoveField(
            model_name='request',
            name='search_parameters',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='InquiryReason',
        ),
        migrations.DeleteModel(
            name='ReportParameters',
        ),
        migrations.DeleteModel(
            name='RequestParameters',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='SearchParameters',
        ),
    ]
